CREATE DATABASE MiniPloomes
GO

USE MiniPloomes;

CREATE TABLE Users (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(max) NOT NULL,
	Email NVARCHAR(max) NOT NULL,
	Password NVARCHAR(max) NOT NULL,
	Token NVARCHAR(max) NULL,
	CreateDate DATETIME2(7) NOT NULL
)
GO

CREATE TABLE Contacts(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(40) NOT NULL,
	CreatorId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	CreateDate DATETIME2(7) NOT NULL
)
GO

CREATE TABLE Deals(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(max) NOT NULL,
	Amount DECIMAL(19,4) CHECK(Amount >= 0) NOT NULL,
	ContactId INT FOREIGN KEY REFERENCES Contacts(Id) NOT NULL,
	CreatorId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	CreateDate DATETIME2(7) NOT NULL
)
GO