/*Alterações posteriores na tabela*/

Use MiniPloomes;

ALTER TABLE [dbo].[Users]
ALTER COLUMN Token NVARCHAR(254) NULL

ALTER TABLE [dbo].[Users]
ADD CONSTRAINT UC_Token UNIQUE (Token);
GO

ALTER TABLE [dbo].[Users]
ALTER COLUMN Email NVARCHAR(254) NOT NULL
GO

ALTER TABLE [dbo].[Users]
ADD CONSTRAINT UC_Email UNIQUE (Email);
GO

ALTER TABLE [dbo].[Contacts]
ALTER COLUMN Name NVARCHAR(max) NOT NULL
GO

ALTER TABLE [dbo].[Contacts]
	DROP CONSTRAINT [FK__Contacts__Creato__3E52440B]
GO

ALTER TABLE [dbo].[Contacts]
	ADD CONSTRAINT FK_CONTACTS_USERS
	FOREIGN KEY (CreatorId) REFERENCES Users(Id) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Deals]
	DROP CONSTRAINT [FK__Deals__ContactId__4222D4EF]
GO

ALTER TABLE [dbo].[Deals]
	DROP CONSTRAINT [FK__Deals__CreatorId__4316F928]
GO

ALTER TABLE [dbo].[Deals]
	ADD CONSTRAINT FK_DEALS_CONTACTS
	FOREIGN KEY (ContactId) REFERENCES Contacts(Id) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Deals]
	ADD CONSTRAINT FK_DEALS_USERS
	FOREIGN KEY (CreatorId) REFERENCES Users(Id)
GO